import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../core/user_model.dart';

class PdfService {
  /// Generates a personalized health plan PDF
  static Future<File> generateHealthPlan(UserData user, String planType, List<String> exercises) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(40),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('VitaAI Health Plan', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                pw.SizedBox(height: 20),
                pw.Divider(),
                pw.SizedBox(height: 20),
                pw.Text('User Details:', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Text('Name: ${user.name}'),
                pw.Text('Age: ${user.age}'),
                pw.Text('Weight: ${user.weight ?? "N/A"} kg'),
                pw.Text('Height: ${user.height ?? "N/A"} cm'),
                pw.SizedBox(height: 20),
                pw.Text('Nutritional Profile (Daily Targets):', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.Text('• Calcium: 1000 mg'),
                pw.Text('• Protein: 80 g'),
                pw.Text('• Water: 3.5 L'),
                pw.SizedBox(height: 30),
                pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  color: PdfColors.blue100,
                  child: pw.Text('Recommended $planType Plan', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                ),
                pw.SizedBox(height: 10),
                ...exercises.map((e) => pw.Bullet(text: e)),
                pw.Spacer(),
                pw.Divider(),
                pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text('Generated by VitaAI Healthcare System', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                ),
              ],
            ),
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/${planType.toLowerCase()}_plan_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  /// Generates a payment receipt for demo consultations
  static Future<File> generateConsultationReceipt(UserData user, String specialistName, double amount) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(40),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('VitaAI Payment Receipt', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                    pw.Container(
                      padding: const pw.EdgeInsets.all(4),
                      decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.green)),
                      child: pw.Text('PAID', style: pw.TextStyle(color: PdfColors.green, fontWeight: pw.FontWeight.bold)),
                    ),
                  ],
                ),
                pw.SizedBox(height: 30),
                pw.Text('Transaction ID: VITA-${DateTime.now().millisecondsSinceEpoch}'),
                pw.Text('Date: ${DateTime.now().toString().split('.')[0]}'),
                pw.SizedBox(height: 20),
                pw.Divider(),
                pw.SizedBox(height: 20),
                pw.Text('Patient: ${user.name}'),
                pw.Text('Specialist: $specialistName'),
                pw.Text('Service: 15-Minute Demo Consultation'),
                pw.SizedBox(height: 30),
                 pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Total Amount:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                    pw.Text('₹$amount', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  ],
                ),
                pw.Spacer(),
                pw.Center(child: pw.Text('Thank you for choosing VitaAI!', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600))),
              ],
            ),
          );
        },
      ),
    );

    final output = await getExternalStorageDirectory();
    final file = File("${output!.path}/consultation_receipt_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
